#!/bin/bash

main() {
    /usr/bin/xinit /usr/bin/plexmediaplayer -- -nocursor :0 -nolisten tcp -s off

    local excode=$?
    if [[ "${excode}" == "0" ]]
    then
        /usr/sbin/poweroff
    fi
}

main
